import 'package:flutter/material.dart';

import 'task_notifications_engine.dart';

/// TaskNotificationDispatcher is responsible for delivering
/// notifications generated by TaskNotificationsEngine.
///
/// This is an internal dispatcher:
/// - In-app banners
/// - Snackbars
/// - Overlays
/// - Daily briefing popups
/// - End-of-day summaries
///
/// OS-level notifications will be added later.
class TaskNotificationDispatcher {
  // Singleton
  static final TaskNotificationDispatcher instance =
      TaskNotificationDispatcher._internal();
  TaskNotificationDispatcher._internal();

  final _engine = TaskNotificationsEngine.instance;

  // -----------------------------
  // SHOW OVERDUE NUDGES
  // -----------------------------
  void showOverdueNudges(BuildContext context) {
    final nudges = _engine.overdueNudges(DateTime.now());
    for (final n in nudges) {
      _banner(context, n);
    }
  }

  // -----------------------------
  // SHOW DUE TODAY ALERTS
  // -----------------------------
  void showDueTodayAlerts(BuildContext context) {
    final alerts = _engine.dueTodayAlerts(DateTime.now());
    for (final a in alerts) {
      _banner(context, a);
    }
  }

  // -----------------------------
  // SHOW NEXT BEST ACTION PROMPT
  // -----------------------------
  void showNextBestAction(BuildContext context) {
    final msg = _engine.nextBestActionPrompt(DateTime.now());
    if (msg != null) {
      _banner(context, msg);
    }
  }

  // -----------------------------
  // SHOW DAILY BRIEFING
  // -----------------------------
  void showDailyBriefing(BuildContext context) {
    final msg = _engine.dailyBriefing(DateTime.now());
    _dialog(context, "Daily Briefing", msg);
  }

  // -----------------------------
  // SHOW END OF DAY SUMMARY
  // -----------------------------
  void showEndOfDaySummary(BuildContext context) {
    final msg = _engine.endOfDaySummary(DateTime.now());
    _dialog(context, "End of Day Summary", msg);
  }

  // -----------------------------
  // SHOW MODE-AWARE PROMPT
  // -----------------------------
  void showModePrompt(BuildContext context, String mode) {
    final msg = _engine.modePrompt(mode, DateTime.now());
    if (msg != null) {
      _banner(context, msg);
    }
  }

  // -----------------------------
  // INTERNAL UI HELPERS
  // -----------------------------
  void _banner(BuildContext context, String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        duration: const Duration(seconds: 4),
      ),
    );
  }

  void _dialog(BuildContext context, String title, String message) {
    showDialog(
      context: context,
      builder: (_) {
        return AlertDialog(
          backgroundColor: Colors.black,
          title: Text(
            title,
            style: const TextStyle(color: Colors.white),
          ),
          content: Text(
            message,
            style: const TextStyle(color: Colors.white70),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text(
                "Close",
                style: TextStyle(color: Colors.tealAccent),
              ),
            ),
          ],
        );
      },
    );
  }
}
