import 'package:flutter/material.dart';
import '../universal/developer_logger.dart';

/// DeveloperLogStore
/// ------------------
/// Stores all developer logs in memory.
/// Singleton.
class DeveloperLogStore {
  static final DeveloperLogStore instance = DeveloperLogStore._internal();
  DeveloperLogStore._internal();

  final List<String> _logs = [];

  List<String> get logs => List.unmodifiable(_logs);

  void add(String message) {
    final timestamp = DateTime.now().toIso8601String();
    _logs.insert(0, "[$timestamp] $message");
  }

  void clear() {
    _logs.clear();
  }
}

/// DeveloperLogsScreen
/// --------------------
/// Shows all logs generated by the system.
/// Useful for debugging internal behavior.
class DeveloperLogsScreen extends StatefulWidget {
  const DeveloperLogsScreen({super.key});

  @override
  State<DeveloperLogsScreen> createState() => _DeveloperLogsScreenState();
}

class _DeveloperLogsScreenState extends State<DeveloperLogsScreen> {
  @override
  void initState() {
    super.initState();
    DeveloperLogger.log("Opened Developer Logs Screen");
  }

  @override
  Widget build(BuildContext context) {
    final store = DeveloperLogStore.instance;

    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        title: const Text("Developer Logs"),
        backgroundColor: Colors.black,
        actions: [
          IconButton(
            icon: const Icon(Icons.delete_forever),
            onPressed: () {
              store.clear();
              DeveloperLogger.log("Developer logs cleared");
              setState(() {});
            },
          ),
        ],
      ),
      body: ListView.builder(
        padding: const EdgeInsets.all(20),
        itemCount: store.logs.length,
        itemBuilder: (context, index) {
          final log = store.logs[index];
          return Container(
            padding: const EdgeInsets.all(14),
            margin: const EdgeInsets.only(bottom: 14),
            decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.05),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              log,
              style: const TextStyle(
                color: Colors.white70,
                height: 1.35,
              ),
            ),
          );
        },
      ),
    );
  }
}
