import '../models/appointment_model.dart';
import '../models/task_model.dart';

class CalendarDayModel {
  final DateTime date;

  final List<AppointmentModel> appointments;
  final List<TaskModel> tasks;

  final int emotionalLoadScore; // aggregated from tasks + appointments
  final int fatigueImpactScore; // aggregated from tasks + appointments
  final int busynessScore; // number of events + duration weighting

  final String aiInsight; // generated by CalendarService

  CalendarDayModel({
    required this.date,
    required this.appointments,
    required this.tasks,
    required this.emotionalLoadScore,
    required this.fatigueImpactScore,
    required this.busynessScore,
    required this.aiInsight,
  });

  CalendarDayModel copyWith({
    List<AppointmentModel>? appointments,
    List<TaskModel>? tasks,
    int? emotionalLoadScore,
    int? fatigueImpactScore,
    int? busynessScore,
    String? aiInsight,
  }) {
    return CalendarDayModel(
      date: date,
      appointments: appointments ?? this.appointments,
      tasks: tasks ?? this.tasks,
      emotionalLoadScore: emotionalLoadScore ?? this.emotionalLoadScore,
      fatigueImpactScore: fatigueImpactScore ?? this.fatigueImpactScore,
      busynessScore: busynessScore ?? this.busynessScore,
      aiInsight: aiInsight ?? this.aiInsight,
    );
  }
}
